version: '3'

services:

  fabio-nginx:
    image: nginx
    ports:
      - "8000:80"
    volumes:
      #diretorio do site
      - ./projeitosite:/usr/share/nginx/html
      - ./site2:/usr/share/nginx/html/site2

      #diretorio do virtualhost
      - ./nginx:/etc/nginx/conf.d/



  fabio-jenkins:
    image: jenkins/jenkins:lts-jdk11
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - ./jenkins:/var/jenkins_home

  
